let pizzaPlace = "Chauncey's Pizza";
let numberOfToppings = 99;
console.log ("pizzaPlace is of type " + typeof pizzaPlace)
console.log ("numberOfToppings is of type" + typeof numberOfToppings)

console.log (`${pizzaPlace} has the most toppings in town. We have ${numberOfToppings} toppings.`)

if (numberOfToppings <= 10){
  console.log ("Quality, not quantity.")
}
else if (numberOfToppings == 99){
console.log ("Dinosaurs Pizza")
}

else {
  console.log ("A whole lot of pizza.")
}

